name = "BoundaryBulkKit"
uuid = "13c682a8-1356-4ba9-a9ff-98b003f00f25"
authors = ["Chenqi Meng <mcqgravity@gmail.com>"]
version = "0.1.0"

[deps]
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TensorKitSectors = "13a9c161-d5da-41f0-bcbd-e1a08ae0647f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
TensorKit = "0"
TensorKitSectors = "0"
LinearAlgebra = "1"